#!/bin/sh
setxkbmap -option caps:swapescape
setxkbmap -option compose:prsc
setxkbmap -layout dvorak

xinput set-prop 12 311 1
xinput set-prop 12 321 .3

feh --bg-scale ~/Pictures/backgrounds/marx.gif

picom -b

sxhkd &

xscreensaver-command -exit

xscreensaver &

xscreensaverstopper &

panel &

pkill polybar

polybar bar &

brightness 100%

redshift &

unclutter &

glava --entry=desktop.glsl &

udiskie --tray &

caffeine &

udiskie &

wmname LG3D

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

xsetroot -cursor_name left_ptr

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then


[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap




    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

xset +fp /home/david/.fonts
xset fp rehash

[[ -f ~/.Xresources ]] && xrdb -I$HOME ~/.Xresources

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
exec bspwm
