# zplug
source ~/.zplug/init.zsh

zplug "zdharma/fast-syntax-highlighting"

zplug "zsh-users/zsh-history-substring-search"

zplug "zsh-users/zsh-autosuggestions"

zplug "geometry-zsh/geometry"

zplug "plugins/colored-man-pages",      from:oh-my-zsh

zplug "plugins/git",                    from:oh-my-zsh

zplug "plugins/archlinux",              from:oh-my-zsh


if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

# aliases
alias v='nvim'
alias vim='nvim'

alias n='nmcli'

alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection

alias q='exit'

alias dotdrop='/home/david/dotfiles/dotdrop.sh --cfg=/home/david/dotfiles/config.yaml'

alias glava-desktop='glava --entry=desktop.glsl'

alias python3.6='python3'

alias hades='wine /home/david/.local/share/Steam/steamapps/common/Hades/x64/Hades.exe'

# keybinds
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

# options
setopt autocd

# plugin setup
eval "$(fasd --init auto)"
eval "$(thefuck --alias)"

# local environment variables
export EDITOR='nvim'
export GEOMETRY_RPROMPT=(git \(virtualenv\))
export GEOMETRY_PROMPT_PLUGINS=()

# highlighting
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#4B4B4B"

# history
HISTFILE=$HOME/.zhistory       # enable history saving on shell exit
setopt APPEND_HISTORY          # append rather than overwrite history file.
HISTSIZE=1200                  # lines of history to maintain memory
SAVEHIST=1000                  # lines of history to maintain in history file.
setopt HIST_EXPIRE_DUPS_FIRST  # allow dups, but expire old ones when I hit HISTSIZE
setopt EXTENDED_HISTORY        # save timestamp and runtime information

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

