#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 ᄁ ᄁ ᄁ ᄁ ᄁ

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_motion_interval     40

bspc rule -r \*

bspc rule -a Zathura state=tiled
bspc rule -a Inkscape desktop='^5'

bspc config external_rules_command "/home/david/.config/bspwm/external_rules"
