config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_config:
    src: config/polybar/config
    dst: ~/.config/polybar/config
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_sxhkdrc:
    src: config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
  f_bspwmrc:
    src: config/bspwm/bspwmrc
    dst: ~/.config/bspwm/bspwmrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_swmap.sh:
    src: scripts/swmap.sh
    dst: ~/scripts/swmap.sh
  f_brightness.sh:
    src: scripts/brightness.sh
    dst: ~/scripts/brightness.sh
  f_spotctl.sh:
    src: scripts/spotctl.sh
    dst: ~/scripts/spotctl.sh
  f_xscreensaverstopper.sh:
    src: scripts/xscreensaverstopper.sh
    dst: ~/scripts/xscreensaverstopper.sh
profiles:
  david:
    dotfiles:
    - f_init.vim
    - f_xinitrc
    - f_config
    - f_alacritty.yml
    - f_sxhkdrc
    - f_bspwmrc
    - f_zshrc
    - f_swmap.sh
    - f_brightness.sh
    - f_spotctl.sh
    - f_xscreensaverstopper.sh
