config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_config:
    src: config/polybar/config
    dst: ~/.config/polybar/config
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_sxhkdrc:
    src: config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
  f_bspwmrc:
    src: config/bspwm/bspwmrc
    dst: ~/.config/bspwm/bspwmrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_swmap.sh:
    src: scripts/swmap.sh
    dst: ~/scripts/swmap.sh
  f_spotctl.sh:
    src: scripts/spotctl.sh
    dst: ~/scripts/spotctl.sh
  f_xscreensaverstopper.sh:
    src: scripts/xscreensaverstopper.sh
    dst: ~/scripts/xscreensaverstopper.sh
  f_marx.gif:
    src: Pictures/backgrounds/marx.gif
    dst: ~/Pictures/backgrounds/marx.gif
  f_rc.glsl:
    src: config/glava/rc.glsl
    dst: ~/.config/glava/rc.glsl
  f_circle.glsl:
    src: config/glava/circle.glsl
    dst: ~/.config/glava/circle.glsl
  f_desktop.glsl:
    src: config/glava/desktop.glsl
    dst: ~/.config/glava/desktop.glsl
  f_radial.glsl:
    src: config/glava/radial.glsl
    dst: ~/.config/glava/radial.glsl
  f_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
profiles:
  david:
    dotfiles:
    - f_init.vim
    - f_xinitrc
    - f_config
    - f_alacritty.yml
    - f_sxhkdrc
    - f_bspwmrc
    - f_zshrc
    - f_swmap.sh
    - f_spotctl.sh
    - f_xscreensaverstopper.sh
    - f_marx.gif
    - f_rc.glsl
    - f_circle.glsl
    - f_desktop.glsl
    - f_radial.glsl
  molamola:
    dotfiles:
    - f_init.vim
    - f_xinitrc
    - f_config
    - f_alacritty.yml
    - f_sxhkdrc
    - f_bspwmrc
    - f_zshrc
    - f_swmap.sh
    - f_spotctl.sh
    - f_xscreensaverstopper.sh
    - f_marx.gif
    - f_rc.glsl
    - f_circle.glsl
    - f_desktop.glsl
    - f_radial.glsl
    - f_config.rasi
